name = "QuEST"
uuid = "51527628-23c9-4c49-801a-ec5650b3540b"
authors = ["Jonathan Miller", "jonathan.miller@fieldofnodes.com"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
