name = "QuEST"
uuid = "2f8c4c1a-2c62-410c-b829-98d6ce53c0c2"
authors = ["Jonathan Miller <jonathan.miller@fieldofnodes.com> and contributors"]
version = "1.0.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuEST_jll = "4a967bbd-a16f-537d-8e95-e68e89d08900"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
TensorOperations = "4.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
